provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  create-user:
    lang: python3-http
    handler: ./create-user
    image: docker.io/lmaye/create-user:latest
    secrets:
      - mysql-pwd
      - fernet-key
    environment:
      MYSQL_HOST: mysql.default.svc.cluster.local
      MYSQL_PWD: /var/openfaas/secrets/mysql-pwd
      FERNET_KEY: /var/openfaas/secrets/fernet-key

  verify-mfa:
    lang: python3-http
    handler: ./verify-mfa
    image: docker.io/lmaye/verify-mfa:latest
    secrets:
      - mysql-pwd
      - fernet-key
    environment:
      MYSQL_HOST: mysql.default.svc.cluster.local
      MYSQL_PWD: /var/openfaas/secrets/mysql-pwd
      FERNET_KEY: /var/openfaas/secrets/fernet-key
      GATEWAY_URL: http://gateway.openfaas:8080

  login:
    lang: python3-http
    handler: ./login
    image: docker.io/lmaye/login:latest
    secrets:
      - mysql-pwd
      - fernet-key
    environment:
      MYSQL_HOST: mysql.default.svc.cluster.local
      MYSQL_PWD: /var/openfaas/secrets/mysql-pwd
      FERNET_KEY: /var/openfaas/secrets/fernet-key

  setup-mfa:
    lang: python3-http
    handler: ./setup-mfa
    image: docker.io/lmaye/setup-mfa:latest
    secrets:
      - mysql-pwd
      - fernet-key
    environment:
      MYSQL_HOST: mysql.default.svc.cluster.local
      MYSQL_PWD: /var/openfaas/secrets/mysql-pwd
      FERNET_KEY: /var/openfaas/secrets/fernet-key

  rotate-password:
    lang: python3-http
    handler: ./rotate-password
    image: docker.io/lmaye/rotate-password:latest
    secrets:
      - mysql-pwd
    environment:
      MYSQL_HOST: mysql.default.svc.cluster.local
      MYSQL_PWD: /var/openfaas/secrets/mysql-pwd
